DROP VIEW v_switch_mod;
DROP VIEW v_switch;
DROP VIEW v_swinfo;
DROP VIEW v_portinfo;
DROP VIEW v_port_list_mod;
DROP VIEW v_port_list;
DROP VIEW v_search_user;
DROP VIEW v_search_mac;
DROP VIEW v_search_outlet;
DROP VIEW v_search_status;
DROP VIEW v_search_status_mod;
DROP VIEW v_search_status_full;
DROP VIEW v_search_status_raw;

DROP FUNCTION fmt_inactivity (interval);
DROP FUNCTION port_order (varchar);

DROP TABLE snmp_entphysicaltable;
DROP TABLE snmp_entaliasmappingtable;
DROP TABLE snmp_cdpcachetable;
DROP TABLE snmp_cafsessiontable;
DROP TABLE permout;
DROP TABLE swstat;
DROP TABLE out2cp;
DROP TABLE modwire;
DROP TABLE mactable;
DROP TABLE hosttab;
DROP TABLE prodstat;
DROP TABLE arptable2;
DROP TABLE status;
DROP TABLE porttable;
